---
title: "R Notebook"
output: html_notebook
---

Data cleaning for predictive modelling in python

Reading in scripts
```{r}
library(tidyverse)
library(janitor)
library(lubridate)
```


Reading in cleaned data
```{r}
activities <- read_csv("clean_data/activities_clean.csv")
demographics <- read_csv("clean_data/demographics_clean.csv")
location <- read_csv("clean_data/location_clean.csv")
transport <- read_csv("clean_data/transport_clean.csv")
```

Cleaning activities dataset - splitting visits and spend into separate datasets
```{r}
activities_visits <- activities %>%
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -spend_unit) %>%
  filter(!is.na(visit_unit))

activities_spend <- activities %>%
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -visit_unit) %>%
  filter(!is.na(spend_unit))
```

Cleaning demo
```{r}
demographics_visits <- demographics %>%
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -spend_unit) %>%
  filter(!is.na(visit_unit))

demographics_spend <- demographics %>% 
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -visit_unit) %>%
  filter(!is.na(spend_unit))
```

```{r}
location_vists <- location %>% 
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -spend_unit) %>%
  filter(!is.na(visit_unit))

location_spend <- location %>% 
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -visit_unit) %>%
  filter(!is.na(spend_unit))
```

```{r}
transport_visits <- transport %>%
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -spend_unit) %>%
  filter(!is.na(visit_unit))

transort_spend <- transport %>%
  mutate(spend_unit = case_when(unit == "million (£)" ~ "million (£)"),
         visit_unit = case_when(unit == "million" ~ "million")) %>%
  select(-unit, -breakdown_of_domestic_tourism, -visit_unit) %>%
  filter(!is.na(spend_unit))
```



